export const connectionTypeObj = {
  IMPORT: "IMPORT",
  EXPORT: "EXPORT"
};
export const connectionProtocolsObj = {
  "SMB Share": "SMB Share",
  SMB: "SMB",
  SFTP: "SFTP",
  Email: "Email",
  FTP: "FTP"
};

export const data = [
  {
    sdpNames: [],
    id: 4075,
    connectionName: "dd",
    connectionType: "EXPORT",
    sdpIds: [],
    protocol: "FTP",
    host: "dd",
    port: null,
    userName: "d",
    password: "",
    sshFingerPrint: "",
    isSsl: false
  },
  {
    sdpNames: [],
    id: 4081,
    connectionName: "De",
    connectionType: "EXPORT",
    sdpIds: [],
    protocol: "Email",
    host: "ee",
    port: 1,
    userName: "eee",
    password: "",
    sshFingerPrint: "",
    isSsl: false
  },
  {
    sdpNames: [],
    id: 4082,
    connectionName: "eee",
    connectionType: "EXPORT",
    sdpIds: [],
    protocol: "FTP",
    host: "ee",
    port: 0,
    userName: "eee",
    password: "",
    sshFingerPrint: "",
    isSsl: false
  },
  {
    sdpNames: [],
    id: 4055,
    connectionName: "EMAIL | TESTING",
    connectionType: "EXPORT",
    sdpIds: [],
    protocol: "Email",
    host: "outlook.office365.com",
    port: 588,
    userName: "mb_riskire@gmail.com",
    password: "",
    sshFingerPrint: "",
    isSsl: false
  },
  {
    sdpNames: [],
    id: 4064,
    connectionName: "EMAIL | TESTING | 1",
    connectionType: "EXPORT",
    sdpIds: [],
    protocol: "Email",
    host: "outlook.office365.com",
    port: 587,
    userName: "mb_riskire@gmail.com",
    password: "",
    sshFingerPrint: null,
    isSsl: false
  },
  {
    sdpNames: [],
    id: 4071,
    connectionName: "EMAIL | TESTING | 2",
    connectionType: "EXPORT",
    sdpIds: [],
    protocol: "Email",
    host: "outlook.office365.com",
    port: 0,
    userName: "mb_riskire@gmail.com",
    password: "",
    sshFingerPrint: "",
    isSsl: false
  },
  {
    sdpNames: [],
    id: 4072,
    connectionName: "EMAIL | TESTING | 3",
    connectionType: "EXPORT",
    sdpIds: [],
    protocol: "Email",
    host: "outlook.office365.com",
    port: 800,
    userName: "mb_riskire@gmail.com",
    password: "",
    sshFingerPrint: "",
    isSsl: false
  },
  {
    sdpNames: [],
    id: 4073,
    connectionName: "EMAIL | TESTING | 5",
    connectionType: "EXPORT",
    sdpIds: [],
    protocol: "Email",
    host: "outlook.office365.com",
    port: 0,
    userName: "mb_riskire@gmail.com",
    password: "",
    sshFingerPrint: "",
    isSsl: false
  },
  {
    sdpNames: [],
    id: 6,
    connectionName: "Export12",
    connectionType: "EXPORT",
    sdpIds: [],
    protocol: "SFTP",
    host: "198.168.102.189",
    port: 8000,
    userName: "Export1",
    password: "",
    sshFingerPrint: "ssh..................",
    isSsl: false
  },
  {
    sdpNames: [],
    id: 4079,
    connectionName: "iii",
    connectionType: "EXPORT",
    sdpIds: [],
    protocol: "FTP",
    host: "ii",
    port: 0,
    userName: "iii",
    password: "",
    sshFingerPrint: "",
    isSsl: false
  },
  {
    sdpNames: [],
    id: 4080,
    connectionName: "kk1",
    connectionType: "EXPORT",
    sdpIds: [],
    protocol: "Email",
    host: "pp",
    port: 0,
    userName: "pp",
    password: "",
    sshFingerPrint: "",
    isSsl: false
  },
  {
    sdpNames: [],
    id: 4077,
    connectionName: "l",
    connectionType: "EXPORT",
    sdpIds: [],
    protocol: "Email",
    host: "l",
    port: 0,
    userName: "ll",
    password: "",
    sshFingerPrint: "",
    isSsl: false
  },
  {
    sdpNames: [],
    id: 4076,
    connectionName: "pp",
    connectionType: "EXPORT",
    sdpIds: [],
    protocol: "FTP",
    host: "p",
    port: 123,
    userName: "p",
    password: "",
    sshFingerPrint: "",
    isSsl: false
  },
  {
    sdpNames: [],
    id: 4087,
    connectionName: "R1",
    connectionType: "EXPORT",
    sdpIds: [],
    protocol: "FTP",
    host: "w",
    port: 0,
    userName: "ww",
    password: "",
    sshFingerPrint: "",
    isSsl: false
  },
  {
    sdpNames: [],
    id: 4061,
    connectionName: "SMB | Insight",
    connectionType: "EXPORT",
    sdpIds: [],
    protocol: "SMB",
    host: "'Hello",
    port: 0,
    userName: "sys_riskhost",
    password: "",
    sshFingerPrint: null,
    isSsl: false
  },
  {
    sdpNames: [],
    id: 4053,
    connectionName: "SMB | TESTING",
    connectionType: "EXPORT",
    sdpIds: [],
    protocol: "SMB",
    host: "\\\\dms.local\\file\\zz.Archive",
    port: 0,
    userName: "sys_riskhost",
    password: "",
    sshFingerPrint: null,
    isSsl: false
  },
  {
    sdpNames: [],
    id: 4059,
    connectionName: "SMB | WAY299 | Testing",
    connectionType: "EXPORT",
    sdpIds: [],
    protocol: "SMB",
    host: "\\\\dms.local\\file\\",
    port: 0,
    userName: "sys_riskhost",
    password: "",
    sshFingerPrint: null,
    isSsl: false
  },
  {
    sdpNames: [],
    id: 4056,
    connectionName: "SMB | Gatestone Internal",
    connectionType: "EXPORT",
    sdpIds: [],
    protocol: "SMB",
    host: "\\\\dms.local\\file\\",
    port: 0,
    userName: "sys_riskhost",
    password: "",
    sshFingerPrint: null,
    isSsl: false
  },
  {
    sdpNames: [],
    id: 7,
    connectionName: "SMB Test",
    connectionType: "EXPORT",
    sdpIds: [],
    protocol: "FTP",
    host: "HostTesdt",
    port: 11122,
    userName: "test@test.com",
    password: "",
    sshFingerPrint: "",
    isSsl: false
  },
  {
    sdpNames: [],
    id: 2,
    connectionName: "SMB TESTING",
    connectionType: "EXPORT",
    sdpIds: [],
    protocol: "SMB",
    host: "\\\\Herry\\WMP Destination",
    port: 0,
    userName: "Herry",
    password: "",
    sshFingerPrint: "",
    isSsl: false
  },
  {
    sdpNames: [],
    id: 3,
    connectionName: "SMB TESTING1",
    connectionType: "EXPORT",
    sdpIds: [],
    protocol: "SMB",
    host: "S-AIE-P-SQ1 NT Prime Herry",
    port: 445,
    userName: "dpal",
    password: "",
    sshFingerPrint: "",
    isSsl: false
  },
  {
    sdpNames: [],
    id: 4069,
    connectionName: "TEST",
    connectionType: "EXPORT",
    sdpIds: [],
    protocol: "SMB",
    host: "192.168.2.33",
    port: 0,
    userName: "mb_riskire@gmail.com",
    password: "",
    sshFingerPrint: "",
    isSsl: false
  },
  {
    sdpNames: [],
    id: 4070,
    connectionName: "TEST test",
    connectionType: "EXPORT",
    sdpIds: [],
    protocol: "FTP",
    host: "192.168.2.33",
    port: 587,
    userName: "mb_riskire@gmail.com",
    password: "",
    sshFingerPrint: "",
    isSsl: false
  },
  {
    sdpNames: [],
    id: 4068,
    connectionName: "TestJOb9",
    connectionType: "EXPORT",
    sdpIds: [],
    protocol: "FTP",
    host: "198.168.102.189",
    port: 8000,
    userName: "test@test.com",
    password: "",
    sshFingerPrint: "",
    isSsl: false
  },
  {
    sdpNames: [],
    id: 8,
    connectionName: "ytest",
    connectionType: "EXPORT",
    sdpIds: [],
    protocol: "Email",
    host: "testhost",
    port: 123,
    userName: "fff@qqqq.com",
    password: "",
    sshFingerPrint: "",
    isSsl: false
  },
  {
    sdpNames: ["APEX", "CITCO"],
    id: 4065,
    connectionName: "aa2",
    connectionType: "IMPORT",
    sdpIds: [3, 5],
    protocol: "FTP",
    host: "2",
    port: 22,
    userName: "2222@wwe.com",
    password: "",
    sshFingerPrint: "",
    isSsl: false
  },
  {
    sdpNames: [],
    id: 4048,
    connectionName: "ALPS | SMB | Test",
    connectionType: "IMPORT",
    sdpIds: [],
    protocol: "SMB",
    host: "\\\\S-aie-t-apprsk1\\alps",
    port: 0,
    userName: "DMS_ORG\\hst_dev",
    password: "",
    sshFingerPrint: null,
    isSsl: false
  },
  {
    sdpNames: [],
    id: 4032,
    connectionName: "BBH | PZENA",
    connectionType: "IMPORT",
    sdpIds: [],
    protocol: "SMB",
    host: "\\\\dms-ire-na2\\vol_",
    port: 445,
    userName: "test",
    password: "",
    sshFingerPrint: null,
    isSsl: false
  },
  {
    sdpNames: ["ALPS  1", "TT International"],
    id: 4,
    connectionName: "BBH | PZENA | Gatestone",
    connectionType: "IMPORT",
    sdpIds: [1, 2],
    protocol: "SMB",
    host: "\\S-aie-t-apprsk1_alps",
    port: 445,
    userName: "aali",
    password: "",
    sshFingerPrint: "",
    isSsl: false
  },
  {
    sdpNames: [],
    id: 4043,
    connectionName: "CENTAUR | TT",
    connectionType: "IMPORT",
    sdpIds: [],
    protocol: "SMB",
    host: "\\\\dms.local\\file\\",
    port: 0,
    userName: "sys_riskhost",
    password: "",
    sshFingerPrint: null,
    isSsl: false
  },
  {
    sdpNames: ["ALPS  1", "APEX"],
    id: 4062,
    connectionName: "CENTAUR | TT | New",
    connectionType: "IMPORT",
    sdpIds: [1, 3],
    protocol: "SMB",
    host: "\\\\Herry\\WMP Source",
    port: 0,
    userName: "Herry",
    password: "",
    sshFingerPrint: "",
    isSsl: false
  },
  {
    sdpNames: ["BNP", "APEX"],
    id: 4066,
    connectionName: "e",
    connectionType: "IMPORT",
    sdpIds: [4, 3],
    protocol: "SFTP",
    host: "e",
    port: 222,
    userName: "test@mail.com",
    password: "",
    sshFingerPrint: "ddwwd",
    isSsl: false
  },
  {
    sdpNames: ["ALPS  1", "CITCO", "TT International"],
    id: 4085,
    connectionName: "EMAIL | TESTING | 0",
    connectionType: "IMPORT",
    sdpIds: [1, 5, 2],
    protocol: "Email",
    host: "outlook.office365.com",
    port: 0,
    userName: "mb_riskire@gmail.com",
    password: "",
    sshFingerPrint: "",
    isSsl: false
  },
  {
    sdpNames: [],
    id: 4063,
    connectionName: "Email | Gatestone | Caceis",
    connectionType: "IMPORT",
    sdpIds: [],
    protocol: "Email",
    host: "outlook.office365.com",
    port: 993,
    userName: "mb_riskire@gmail.com",
    password: "",
    sshFingerPrint: null,
    isSsl: false
  },
  {
    sdpNames: [],
    id: 4050,
    connectionName: "Email | Gatestone | NT",
    connectionType: "IMPORT",
    sdpIds: [],
    protocol: "Email",
    host: "outlook.office365.com",
    port: 993,
    userName: "mb_riskire@gmail.com",
    password: "",
    sshFingerPrint: null,
    isSsl: false
  },
  {
    sdpNames: ["BNP"],
    id: 1,
    connectionName: "Email Multiple Clients",
    connectionType: "IMPORT",
    sdpIds: [4],
    protocol: "Email",
    host: "outlook.office365.com",
    port: 8080,
    userName: "mb_riskire@hst.com",
    password: "",
    sshFingerPrint: "",
    isSsl: false
  },
  {
    sdpNames: [],
    id: 4031,
    connectionName: "Email Multiple Clients",
    connectionType: "IMPORT",
    sdpIds: [],
    protocol: "Email",
    host: "outlook.office365.com",
    port: 993,
    userName: "mb_riskire@dmsgovernance.com",
    password: "",
    sshFingerPrint: null,
    isSsl: false
  },
  {
    sdpNames: [],
    id: 4054,
    connectionName: "Email Test AA",
    connectionType: "IMPORT",
    sdpIds: [],
    protocol: "Email",
    host: "outlook.office365.com",
    port: 993,
    userName: "mb_riskire@gmail.com",
    password: "",
    sshFingerPrint: null,
    isSsl: false
  },
  {
    sdpNames: [],
    id: 4049,
    connectionName: "FTP | SEI",
    connectionType: "IMPORT",
    sdpIds: [],
    protocol: "SFTP",
    host: "ftp2.seic.com",
    port: 22,
    userName: "DMS_ServiceAccount",
    password: "",
    sshFingerPrint: "ssh-rsa 2048 o9wz/H2Zlga6UpvMw00HwCYm6vS6tp7NNylwIgocJIU=",
    isSsl: false
  },
  {
    sdpNames: [],
    id: 4058,
    connectionName: "Harmonic | SMB",
    connectionType: "IMPORT",
    sdpIds: [],
    protocol: "SMB",
    host: "\\\\dms.local\\file\\",
    port: 0,
    userName: "sys_riskhost",
    password: "",
    sshFingerPrint: null,
    isSsl: false
  },
  {
    sdpNames: ["ALPS  1", "APEX"],
    id: 5,
    connectionName: "ImportTest1",
    connectionType: "IMPORT",
    sdpIds: [1, 3],
    protocol: "Email",
    host: "192.168.2.33",
    port: 3000,
    userName: "ImportUser1",
    password: "",
    sshFingerPrint: "",
    isSsl: false
  },
  {
    sdpNames: ["APEX"],
    id: 4078,
    connectionName: "ooo",
    connectionType: "IMPORT",
    sdpIds: [3],
    protocol: "FTP",
    host: "lll",
    port: 33,
    userName: "ll",
    password: "",
    sshFingerPrint: "",
    isSsl: false
  },
  {
    sdpNames: ["ALPS  1"],
    id: 4088,
    connectionName: "R11",
    connectionType: "IMPORT",
    sdpIds: [1],
    protocol: "Email",
    host: "q",
    port: 0,
    userName: "mk",
    password: "",
    sshFingerPrint: "",
    isSsl: false
  },
  {
    sdpNames: [],
    id: 4051,
    connectionName: "SMB | BNP",
    connectionType: "IMPORT",
    sdpIds: [],
    protocol: "SMB",
    host: "\\\\dms.local\\file\\Risk_FundData_Client",
    port: 0,
    userName: "sys_riskhost",
    password: "",
    sshFingerPrint: null,
    isSsl: false
  },
  {
    sdpNames: [],
    id: 4038,
    connectionName: "SMB | SEI",
    connectionType: "IMPORT",
    sdpIds: [],
    protocol: "SMB",
    host: "\\\\dms-ire-na2\\vol_",
    port: 0,
    userName: "sys_riskhost",
    password: "",
    sshFingerPrint: null,
    isSsl: false
  },
  {
    sdpNames: [],
    id: 4045,
    connectionName: "SMB | State Street",
    connectionType: "IMPORT",
    sdpIds: [],
    protocol: "SMB",
    host: "\\\\dms-ire-na2\\vol_",
    port: 0,
    userName: "sys_riskhost",
    password: "",
    sshFingerPrint: null,
    isSsl: false
  },
  {
    sdpNames: [],
    id: 4052,
    connectionName: "SMB | UAT TESTING",
    connectionType: "IMPORT",
    sdpIds: [],
    protocol: "SMB",
    host: "\\\\dms.local\\file\\zz.Archive\\",
    port: 0,
    userName: "sys_riskhost",
    password: "",
    sshFingerPrint: null,
    isSsl: false
  },
  {
    sdpNames: [],
    id: 4060,
    connectionName: "SMB | WAY583 | Testing",
    connectionType: "IMPORT",
    sdpIds: [],
    protocol: "SMB",
    host: "\\\\S-AIE-U-WEBRSK3\\WMPSMBShare",
    port: 0,
    userName: "dpal",
    password: "",
    sshFingerPrint: null,
    isSsl: false
  },
  {
    sdpNames: [],
    id: 4033,
    connectionName: "SS IFS | DEMO",
    connectionType: "IMPORT",
    sdpIds: [],
    protocol: "SMB",
    host: "\\\\dms-ire-na2\\vol_",
    port: 0,
    userName: "test",
    password: "",
    sshFingerPrint: null,
    isSsl: false
  },
  {
    sdpNames: ["ALPS  1"],
    id: 4083,
    connectionName: "ss123",
    connectionType: "IMPORT",
    sdpIds: [1],
    protocol: "Email",
    host: "ss",
    port: 0,
    userName: "sss",
    password: "",
    sshFingerPrint: "",
    isSsl: false
  },
  {
    sdpNames: [],
    id: 4046,
    connectionName: "TT | EMU",
    connectionType: "IMPORT",
    sdpIds: [],
    protocol: "SMB",
    host: "\\\\dms-ire-na2\\vol_",
    port: 0,
    userName: "sys_riskhost",
    password: "",
    sshFingerPrint: null,
    isSsl: false
  },
  {
    sdpNames: [],
    id: 4034,
    connectionName: "TT International",
    connectionType: "IMPORT",
    sdpIds: [],
    protocol: "SMB",
    host: "\\\\dms-ire-na2\\vol_",
    port: 0,
    userName: "sys_riskhost",
    password: "",
    sshFingerPrint: null,
    isSsl: false
  },
  {
    sdpNames: ["ALPS  1", "APEX", "BNP", "CITCO"],
    id: 4067,
    connectionName: "ww",
    connectionType: "IMPORT",
    sdpIds: [1, 3, 4, 5],
    protocol: "FTP",
    host: "ww",
    port: 100,
    userName: "wwww",
    password: "",
    sshFingerPrint: "",
    isSsl: false
  }
];
